apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    vendor: "dorshaar"
  name: tasker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-api
  template:
    metadata:
      labels:
        app: tasker-api
    spec:
      containers:
      - name: tasker-api
        image: dorshaar/tasker-api:1.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 1500Mi
        ports:
        - containerPort: 8080
