apiVersion: v1
kind: Service
metadata:
  labels:
    vendor: dorshaar
  name: tasker-api
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tasker-api
  sessionAffinity: None
  type: NodePort