DatabaseDirectoryPath: C:\Users\Public\DorShaar\C#Work\TaskManagerApp\TaskerStorage\database
NotesDirectoryPath: C:\Users\Public\DorShaar\C#Work\TaskManagerApp\TaskerStorage\general_notes
NotesTasksDirectoryPath: C:\Users\Public\DorShaar\C#Work\TaskManagerApp\TaskerStorage\tasks
DefaultTasksGroup: