apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasker-pv
  labels:
    type: local
spec:
  storageClassName: manual
  PersistentVolumeClaim: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/C/Users/Public/DorShaar/C#Work/TaskManagerApp/TaskerStorage"

# path: "/C/Users/dor.shaar/OneDrive - Votiro/Dor/Notes"