apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasker-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/C/Users/dor.shaar/OneDrive - Votiro/Dor/Notes"